### ISSUE TITLE
error: [Error Code: 1054] location (undefined) is not a valid location: expecting an AddressLocation, but other location types are passed

### ISSUE THREAD

**Issue by fubz** [onflow/fcl-dev-wallet#85]
Signup and Login to wallet does not work and only throws the error:
error: [Error Code: 1054] location (undefined) is not a valid location: expecting an AddressLocation, but other location types are passed

**Comment by alse** [comment]
@fubz make sure you have all the env variables from https://github.com/onflow/fcl-dev-wallet/blob/main/.env.example

**Comment by fubz** [comment]
I created the following docker-compose.yml based upon the one in the project and added in the missing env variables. What's interesting is if I run the emulator and wallet using the cli with `flow project start-emulator ./flow.json --dev-wallet` the wallet works as expected.

```
version: "3"
services:
  wallet:
    image: ghcr.io/onflow/fcl-dev-wallet:latest
    ports:
      - "8701:8701"
    environment:
      - PORT=8701
      - BASE_URL=http://localhost:8701
      - FLOW_ACCESS_NODE=http://emulator:8080
      - FLOW_ACCOUNT_KEY_ID=0
      - FLOW_ACCOUNT_PRIVATE_KEY=84f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5
      - FLOW_ACCOUNT_PUBLIC_KEY=4519e9fbf966c6589fafe60903c0da5f55c5cb50aee5d870f097b35dfb6de13c170718cd92f50811cdd9290e51c2766440b696e0423a5031ae482cca79e3c479
      - FLOW_INIT_ACCOUNTS=1
      - FLOW_ACCOUNT_ADDRESS=0xf8d6e0586b0a20c7
      - FLOW_AVATAR_URL=https://avatars.onflow.org/avatar/
      - CONTRACT_FUNGIBLE_TOKEN=0xee82856bf20e2aa6
      - CONTRACT_FLOW_TOKEN=0x0ae53cb6e3f42a79
      - CONTRACT_FUSD=0xf8d6e0586b0a20c7
      - TOKEN_AMOUNT_FLOW=10000.0
      - TOKEN_AMOUNT_FUSD=10000.0
  emulator:
    image: gcr.io/flow-container-registry/emulator:latest
    ports:
      - "8080:8080"
      - "3569:3569"
    environment:
      - FLOW_SERVICEPRIVATEKEY=84f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256

```

The above docker-compose still results in the web browser encountering an HTTP 500 with the following errors in the emulator/wallet logs.

```
[+] Running 2/0
 ⠿ Container stepone-emulator-1  Created                                                                                                                                                                     0.0s
 ⠿ Container stepone-wallet-1    Created                                                                                                                                                                     0.0s
Attaching to stepone-emulator-1, stepone-wallet-1
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="⚙️   Using service account 0xf8d6e0586b0a20c7" serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=84f82df6790f07b281adb5bbc848bd6298a2de67f94bdfac7a400d5a1b893de5 servicePubKey=4519e9fbf966c6589fafe60903c0da5f55c5cb50aee5d870f097b35dfb6de13c170718cd92f50811cdd9290e51c2766440b696e0423a5031ae482cca79e3c479 serviceSigAlgo=ECDSA_P256
stepone-wallet-1    | 
stepone-wallet-1    | > fcl-dev-wallet@0.3.0 start
stepone-wallet-1    | > next start
stepone-wallet-1    | 
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="📜  Flow contract" FlowServiceAccount=0xf8d6e0586b0a20c7
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="📜  Flow contract" FlowToken=0x0ae53cb6e3f42a79
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="📜  Flow contract" FungibleToken=0xee82856bf20e2aa6
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="📜  Flow contract" FlowFees=0xe5a8b7f23e8b548f
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="📜  Flow contract" FlowStorageFees=0xf8d6e0586b0a20c7
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="🌱  Starting gRPC server on port 3569" port=3569
stepone-emulator-1  | time="2022-01-14T01:08:48Z" level=info msg="🌱  Starting HTTP server on port 8080" port=8080
stepone-wallet-1    | ready - started server on 0.0.0.0:8701, url: http://localhost:8701
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="❗  Script reverted" scriptID=9f27bcf1d399d777a8b9c7c08c9ee3e9a4346820c29af2247b86781d509104df
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="\x1b[1;31mERR\x1b[0m \x1b[2m[9f27bc]\x1b[0m [Error Code: 1101] cadence runtime error Execution failed:\nerror: cannot find declaration `FCL` in `f8d6e0586b0a20c7.FCL`\n --> 9f27bcf1d399d777a8b9c7c08c9ee3e9a4346820c29af2247b86781d509104df:1:7\n  |\n1 | import FCL from 0xf8d6e0586b0a20c7\n  |        ^^^ available exported declarations are:\n\n"
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="❗  Transaction reverted" computationUsed=0 txID=2cda3f3642075975cf6216fad30c4e38e087a6b20d996bca9944556e4b8410d7
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="\x1b[1;31mERR\x1b[0m \x1b[2m[2cda3f]\x1b[0m [Error Code: 1101] cadence runtime error Execution failed:\nerror: cannot find declaration `FUSD` in `f8d6e0586b0a20c7.FUSD`\n --> 2cda3f3642075975cf6216fad30c4e38e087a6b20d996bca9944556e4b8410d7:1:7\n  |\n1 | import FUSD from 0xf8d6e0586b0a20c7\n  |        ^^^^ available exported declarations are:\n\n"
stepone-wallet-1    | TX:ERROR execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:
stepone-wallet-1    | error: cannot find declaration `FUSD` in `f8d6e0586b0a20c7.FUSD`
stepone-wallet-1    |  --> 2cda3f3642075975cf6216fad30c4e38e087a6b20d996bca9944556e4b8410d7:1:7
stepone-wallet-1    |   |
stepone-wallet-1    | 1 | import FUSD from 0xf8d6e0586b0a20c7
stepone-wallet-1    |   |        ^^^^ available exported declarations are:
stepone-wallet-1    | 
stepone-wallet-1    | 
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="❗  Script reverted" scriptID=9f27bcf1d399d777a8b9c7c08c9ee3e9a4346820c29af2247b86781d509104df
stepone-emulator-1  | time="2022-01-14T01:08:59Z" level=warning msg="\x1b[1;31mERR\x1b[0m \x1b[2m[9f27bc]\x1b[0m [Error Code: 1101] cadence runtime error Execution failed:\nerror: cannot find declaration `FCL` in `f8d6e0586b0a20c7.FCL`\n --> 9f27bcf1d399d777a8b9c7c08c9ee3e9a4346820c29af2247b86781d509104df:1:7\n  |\n1 | import FCL from 0xf8d6e0586b0a20c7\n  |        ^^^ available exported declarations are:\n\n"
```
